main:
  - name: home
    url: /
    weight: 100

  - name: certificate
    url: certificate
    weight: 200

  - name: project
    url: project
    weight: 300

  - name: etc
    url: etc
    weight: 400

  - name: interest
    url: etc/interest
    weight: 410

  - name: music
    url: etc/music
    weight: 420

  - name: contact
    url: contact
    weight: 700
